---
deployment:
  tasks:
    - "export DEPLOYPATH=/home1/bgyakwmy/public_html/website_aae26e63/"
    - "/bin/cp -R dist/images $DEPLOYPATH"
    - "/bin/cp dist/index.html $DEPLOYPATH"
    - "/bin/cp dist/main.js $DEPLOYPATH"
    - "/bin/cp favicon.ico $DEPLOYPATH"
