---
deployment:
  tasks:
    - "export DEPLOYPATH=/home1/bgyakwmy/public_html/website_aae26e63/"
    - "/bin/cp -R images $DEPLOYPATH"
    - "/bin/cp index.js $DEPLOYPATH"
    - "/bin/cp index.html $DEPLOYPATH"
    - "/bin/cp style.css $DEPLOYPATH"
